- name: Installing Mongodb
  hosts: mongodb
  become: yes
  tasks: 
  - name: Copying mongo.repo file
    ansible.builtin.copy: 
      src: mongo.repo
      dest: /etc/yum.repos.d/mongo.repo

  - name: Installing MongoDB
    ansible.builtin.yum:
      name: mongodb-org
      state: installed

  - name: Start & Enable MongoDB Service
    ansible.builtin.service:
      name: mongod
      state: started
      enabled: yes

  - name: Update listen address from 127.0.0.1 to 0.0.0.0 in /etc/mongod.conf
    ansible.builtin.replace:
      path: /etc/mongod.conf
      regexp: '127.0.0.1'
      replace: '0.0.0.0'

  - name: restart mongodb
    ansible.builtin.service:
      name: mongod
      state: restarted

  - name: Checking port is availble or not
    ansible.builtin.shell:
      cmd:  netstat -tnlp 